version: '3.8'

services:
  roastmyportfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"    
      - "8080:8080"  
    env_file:
      - .env.production
      - backend/.env.production
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8080/health && curl -f http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend-data:
